name: Deploy React app to GitHub Pages

on:
  push:
    branches:
      - main # Or master, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "nishal"
          git config --global user.email "nishal17@github.com"
          git remote add origin https://github.com/nishal-nm/nishal-portfolio.git
          git add -A
          git commit -m "Deploy React app to GitHub Pages"
          git push -f origin main:gh-pages
